name: Package Addon
 
on:
  push:
    tags:
      - "v*"
 
jobs:
  package:
    runs-on: ubuntu-latest
 
  permissions:
    contents: write
 
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
 
    - name: Package
      uses: BigWigsMods/packager@v2
      env:
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
